# Generated by Django 5.2.1 on 2025-05-18 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fyers_Auth_Inputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, max_length=50, null=True)),
                ('secret_id', models.CharField(blank=True, max_length=50, null=True)),
                ('redirect_url', models.CharField(default='https://trade.fyers.in/api-login/redirect-uri/index.html', max_length=100)),
                ('user_ass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fyers_Access_Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_code', models.CharField(blank=True, max_length=1500, null=True)),
                ('app_ass', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.fyers_auth_inputs')),
            ],
        ),
    ]
